import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { PropsWithChildren } from "react";
import localFont from 'next/font/local'

const chillax = localFont({
  src: '../../public/fonts/Chillax-Variable.ttf',
  variable: '--font-chillax'
})

const archivo = localFont({
  src: '../../public/fonts/Archivo-Variable.ttf',
  variable: '--font-archivo'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: PropsWithChildren<{}>) {
  return (
    <html lang="en">
      <body className={`${chillax.variable} ${archivo.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}